services:
  db:
    image: postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    container_name: postgres-db
    restart: always

  qdrant:
    image: qdrant/qdrant:v1.14.1
    container_name: qdrant
    ports:
      - "6333:6333"
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:6333/collections" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure
    volumes:
      - qdrant_db:/qdrant/storage

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s

  celery_worker:
    entrypoint: ""
    build: .
    container_name: celery-worker
    command: celery -A blt worker -l info
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - .:/blt
    restart: on-failure
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    container_name: app
    restart: on-failure
    env_file:
      - .env
    volumes:
      - .:/blt
    ports:
      - "${PORT}:8000"
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    command: ./entrypoint.sh

  init:
    profiles:
      - init
    build: .
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - .:/blt
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    command: ./entrypoint.sh

volumes:
  postgres_db:
  qdrant_db:
