services:
  db:
    image: postgres:17.6
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    container_name: postgres-db
    restart: always

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    container_name: app
    restart: on-failure
    env_file:
      - .env
    volumes:
      - .:/blt
    ports:
      - "${PORT}:8000"
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    command: ./entrypoint.sh

  cron:
    build: .
    depends_on:
      db:
        condition: service_healthy
    container_name: blt-cron
    restart: always
    env_file:
      - .env
    volumes:
      - .:/blt
      - cron_logs:/var/log
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER:-blt}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB:-blt}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      # Set timezone for cron (adjust as needed)
      - TZ=UTC
    command: >
      sh -c "crontab /blt/crontab && 
             cron && 
             touch /var/log/cron.log &&
             chmod 666 /var/log/cron.log &&
             tail -f /var/log/cron.log"

  init:
    profiles:
      - init
    build: .
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - .:/blt
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    command: ./entrypoint.sh

volumes:
  postgres_db: