version: "3"

services:
  app:
    command: "poetry run python manage.py runserver 0.0.0.0:8000 && python manage.py exec app redis-server"
    build: .
    volumes:
      - .:/blt
    ports:
      - "8000:8000"
