# DOCKER-COMPOSE DISABLED - POETRY ONLY
# Docker is disabled per user request. Use Poetry to run and manage the project locally.
# Commands to run from project root (/Users/aaradhychinche/Documents/blt/BLT):
#
# poetry install
# poetry run pre-commit install
# poetry run pre-commit run --all-files
# poetry run python manage.py migrate --noinput
# poetry run python manage.py collectstatic --noinput
# poetry run python manage.py runserver 0.0.0.0:8000
#
# If you need a Docker setup later, I can re-create a docker-compose file configured for your environment.